name: Re-usable Terraform Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      certPath:
        required: true
        type: string

jobs:
  reusable-terraform-deploy:
    name: Re-usable terraform deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: access file from cache
        env:
          CERT_PATH: ${{ inputs.certPath }}
        run: cat ${CERT_PATH}

      - name: access file from context folder
        run: cat bar/bar.txt
