name: _Re-usable Terraform Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      certPath:
        required: true
        type: string

jobs:
  terraform-deploy:
    name: Re-usable terraform deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Restore cached files
        id: local-file-cache
        uses: actions/cache@v2
        with:
          key: local-files
          path: files

      - name: print cert path
        env:
          CERT_PATH: ${{ inputs.certPath }}
        run: echo ${CERT_PATH}

      - name: access file from cache
        env:
          CERT_PATH: ${{ inputs.certPath }}
        run: cat ${CERT_PATH}

      - name: access file from context folder
        run: cat bar/bar.txt
