name: Context Bar Infra Rollout

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'bar/**'

jobs:
  create-local-files:
    name: Create local files
    uses: andiMenge/actions-explo/.github/workflows/_create-local-files.yml@main

  call-terraform-deploy:
    name: Call the _terraform-deploy re-usable workflow
    needs: create-local-files
    uses: andiMenge/actions-explo/.github/workflows/_terraform-deploy.yml@main
    with:
      certPath: "./files/file-from-script.pem"
